VLLM_ALLREDUCE_USE_FLASHINFER: '0'
VLLM_ALLREDUCE_USE_SYMM_MEM: '0'
VLLM_USE_NCCL_SYMM_MEM: '0'
CUDA_MPS_PIPE_DIRECTORY: /workspace/experiment/mps-sync-pipe
CUDA_MPS_LOG_DIRECTORY: /workspace/experiment/results/mps-sync-logs
CUDA_MPS_ACTIVE_THREAD_PERCENTAGE: '100'
