#!/usr/bin/env bash
# Regenerate fork/patches from the release commits on top of the base tag.
#
#   export-patches.sh <sha>        (env: REPO, BASE_TAG, PATCH_DIR)
#
# Output is byte-reproducible: --zero-commit drops the commit id, --full-index
# drops the abbreviation dependence, the Date: line is the author date. The
# RELEASE file pins the exact commit the files came from.
set -euo pipefail

[ "$#" -eq 1 ] || {
  echo "usage: export-patches.sh <sha>" >&2
  exit 2
}
REPO="${REPO:-$(git -C . rev-parse --show-toplevel)}"
PATCH_DIR="${PATCH_DIR:-$REPO/fork/patches}"
BASE_TAG="${BASE_TAG:-$(sed -n 's/^ARG BASE_TAG=//p' "$REPO/fork/docker/Dockerfile.audio" | head -1)}"
[ -n "$BASE_TAG" ] || {
  echo "ERROR: no base tag (ARG BASE_TAG or \$BASE_TAG)" >&2
  exit 1
}
SHA="$(git -C "$REPO" rev-parse --verify "$1^{commit}")"
BASE="$(git -C "$REPO" rev-parse --verify "$BASE_TAG^{commit}")"
git -C "$REPO" merge-base --is-ancestor "$BASE" "$SHA" || {
  echo "ERROR: $SHA is not descended from $BASE_TAG" >&2
  exit 1
}
mkdir -p "$PATCH_DIR"
find "$PATCH_DIR" -maxdepth 1 -name '*.patch' -delete
git -C "$REPO" format-patch -q -k --full-index --no-renames --zero-commit \
  --no-signature --no-stat -o "$PATCH_DIR" "$BASE..$SHA"
{
  echo "# generated by fork/scripts/export-patches.sh from $SHA; do not edit"
  for file in "$PATCH_DIR"/*.patch; do
    [ -e "$file" ] && basename "$file"
  done
} >"$PATCH_DIR/series"
{
  echo "# generated by fork/scripts/export-patches.sh from $SHA; do not edit"
  echo "# <patch-filename> <Upstream-Merge sha>; patches with Upstream-Merge: none are omitted"
  index=0
  for commit in $(git -C "$REPO" rev-list --reverse "$BASE..$SHA"); do
    index=$((index + 1))
    merge="$(git -C "$REPO" log -1 --format=%B "$commit" |
      git interpret-trailers --parse |
      sed -n 's/^Upstream-Merge: *//p' | head -1)"
    number="$(printf '%04d' "$index")"
    file="$(find "$PATCH_DIR" -maxdepth 1 -name "${number}-*.patch" -printf '%f\n')"
    [ "$merge" != "none" ] && [ -n "$merge" ] && echo "$file $merge"
  done
} >"$PATCH_DIR/upstream.map"
printf 'tag: %s\nrelease-sha: %s\n' "$BASE_TAG" "$SHA" >"$PATCH_DIR/RELEASE"
echo "exported $(git -C "$REPO" rev-list --count "$BASE..$SHA") patch(es) from $SHA into ${PATCH_DIR#"$REPO"/}"
